version: '3'

services:
  app_cafe:
    build: cafe
    container_name: app_cafe
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/cafe?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynet

  db:
    image: mysql:9.0.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: cafe
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: my_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - mynet

volumes:
  mysql_data:

networks:
  mynet:
    driver: bridge